project_id = "lxgcseulhfdlkpskaxfq"

[functions.generate-content]
verify_jwt = false

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.notify-indexnow]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
